server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接池配置
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    show-sql: true

mybatis:
  # mybatis读取的数据源
  datasource:
    testdb:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver

  configuration:
    testdb:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true

common:
  env: 'local'

  thread-pool:
    core-pool-size: 10
    max-pool-size: 20
    keep-alive-time: 10
    queue-capacity: 50
    thread-name-prefix: 'async-thread-'
