server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

mybatis:
  # mybatis读取的数据源
  datasource:
    testdb:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver

  configuration:
    testdb:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true

common:
  env: 'local'

